services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: holiday-swap
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    command: ["postgres", "-c", "shared_preload_libraries=unaccent"]
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
#    command: ["rabbitmq-plugins", "enable", "rabbitmq_stomp"]
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
      - "61613:61613" # STOMP port
    networks:
      - cluster-network
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - cluster-network
    volumes:
      - redis:/data
    restart: always

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - redisinsight:/db
    networks:
      - cluster-network

networks:
  postgres:
    driver: bridge
  cluster-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  rabbitmq:
  redis:
  redisinsight: