spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://awseb-e-ykimbrpgq3-stack-awsebrdsdatabase-pushioghcpm6.cyspfa2bcawq.ap-southeast-1.rds.amazonaws.com:5432/ebdb
    username: dev/cosmetic/postgres
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_nationalized_character_data: true
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}:5672
    stomp:
      port: 61613
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${EMAIL_USERNAME:holidayswap.noreply@gmail.com}
    password: ${EMAIL_PASSWORD:wnummecwjczsyxpx}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate: error

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    email: email.queue
  routing-keys:
    internal-email: internal.email.routing-key

mail:
  debug: true

application:
  base-url: ${BASE_URL:https://api.holiday-swap.click}
  security:
    jwt:
      secret-key: ${JWT_SECRET:8A2F7B9E1D3C5F6A0B2D4F6A8C0E2F4A1B3D5F7A9C0E3F5A2B4D6F8A1B2}
      expiration: ${JWT_EXPIRATION:2592000000} #30 days
      access-token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000} #30 minutes
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1296000000} #15 days
