spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://awseb-e-ykimbrpgq3-stack-awsebrdsdatabase-pushioghcpm6.cyspfa2bcawq.ap-southeast-1.rds.amazonaws.com:5432/ebdb
    username: dev/cosmetic/postgres
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_nationalized_character_data: true
    show-sql: true
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}:5672
    stomp:
      port: 61613
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

logging:
  level:
    org:
      hibernate: error

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    email: email.queue
  routing-keys:
    internal-email: internal.email.routing-key

mail:
  debug: true

redis:
  host: ${HOST:localhost}
  port: 6379

amazon:
  s3:
    bucket:
      name: holiday-swap-file-resouces
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

application:
  host: ${HOST:localhost}
  base-url: ${BASE_URL:http://localhost:8080}
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:2592000000}
      access-token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1296000000}
