CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER       NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)  NOT NULL,
    type           VARCHAR(20)   NOT NULL,
    script         VARCHAR(1000) NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)  NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER       NOT NULL,
    success        BOOLEAN       NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE in_room_amenity
(
    in_room_amenity_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    in_room_amenity_name    TEXT,
    in_room_amenity_type_id BIGINT,
    is_deleted              BOOLEAN DEFAULT FALSE,
    CONSTRAINT in_room_amenity_pkey PRIMARY KEY (in_room_amenity_id)
);

CREATE TABLE in_room_amenity_type
(
    in_room_amenity_type_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    in_room_amenity_type_name TEXT,
    is_deleted                BOOLEAN DEFAULT FALSE,
    CONSTRAINT in_room_amenity_type_pkey PRIMARY KEY (in_room_amenity_type_id)
);

CREATE TABLE location
(
    location_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code           VARCHAR(35)                             NOT NULL,
    coordinates    POINT,
    description    VARCHAR(255),
    formatted_name VARCHAR(255),
    name           VARCHAR(255)                            NOT NULL,
    CONSTRAINT location_pkey PRIMARY KEY (location_id)
);

CREATE TABLE property
(
    property_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted         BOOLEAN DEFAULT FALSE,
    number_baths_room  INTEGER,
    number_beds_room   INTEGER,
    number_full_beds   INTEGER,
    number_king_beds   INTEGER,
    number_murphy_beds INTEGER,
    number_sofa_beds   INTEGER,
    number_twin_beds   INTEGER,
    number_qeen_beds   INTEGER,
    property_type_id   BIGINT,
    property_view_id   BIGINT,
    room_size          FLOAT8,
    room_view_id       BIGINT,
    status             TEXT,
    CONSTRAINT property_pkey PRIMARY KEY (property_id)
);

CREATE TABLE property_type
(
    property_type_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted                BOOLEAN DEFAULT FALSE,
    property_type_description TEXT,
    property_type_name        TEXT,
    resort_id                 BIGINT,
    CONSTRAINT property_type_pkey PRIMARY KEY (property_type_id)
);

CREATE TABLE property_view
(
    property_view_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted                BOOLEAN DEFAULT FALSE,
    property_view_description TEXT,
    property_view_name        TEXT,
    CONSTRAINT property_view_pkey PRIMARY KEY (property_view_id)
);

CREATE TABLE resort_amenity
(
    resort_amenity_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted             BOOLEAN DEFAULT FALSE,
    resort_amenity_name    TEXT,
    resort_amenity_type_id BIGINT,
    CONSTRAINT resort_amenity_pkey PRIMARY KEY (resort_amenity_id)
);

CREATE TABLE resort_amenity_type
(
    resort_amenity_type_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resort_amenity_type_name TEXT,
    is_deleted               BOOLEAN DEFAULT FALSE,
    CONSTRAINT resort_amenity_type_pkey PRIMARY KEY (resort_amenity_type_id)
);

CREATE TABLE admin_wallet
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL,
    total_point FLOAT8,
    CONSTRAINT admin_wallet_pkey PRIMARY KEY (id)
);

CREATE TABLE all_transaction_log
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
    amount       BIGINT                                                 NOT NULL,
    commission   FLOAT8,
    created_on   VARCHAR(255),
    detail       VARCHAR(255),
    from_balance FLOAT8,
    from_id      BIGINT                                                 NOT NULL,
    result_code  SMALLINT,
    to_balance   FLOAT8,
    to_id        BIGINT                                                 NOT NULL,
    CONSTRAINT all_transaction_log_pkey PRIMARY KEY (id)
);

CREATE TABLE contract_image
(
    contract_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted        BOOLEAN,
    link              TEXT,
    ownership_id      BIGINT,
    CONSTRAINT contract_image_pkey PRIMARY KEY (contract_image_id)
);

CREATE TABLE conversation
(
    conversation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT conversation_pkey PRIMARY KEY (conversation_id)
);

CREATE TABLE conversation_participant
(
    conversation_id BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    left_chat       BOOLEAN DEFAULT FALSE,
    CONSTRAINT conversation_participant_pkey PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE message
(
    message_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id       BIGINT                                  NOT NULL,
    date            TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    image           VARCHAR(255),
    message_type    VARCHAR(255),
    text            VARCHAR(255),
    conversation_id BIGINT                                  NOT NULL,
    CONSTRAINT message_pkey PRIMARY KEY (message_id)
);

CREATE TABLE money_transfer
(
    money_transfer_id    BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL,
    amount               FLOAT8                                                 NOT NULL,
    amount_coint_deposit INTEGER,
    bank_code            VARCHAR(255),
    order_infor          VARCHAR(255)                                           NOT NULL,
    payment_date         VARCHAR(255)                                           NOT NULL,
    status               SMALLINT                                               NOT NULL,
    user_id              BIGINT,
    CONSTRAINT money_transfer_pkey PRIMARY KEY (money_transfer_id)
);

CREATE TABLE notification
(
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content         VARCHAR(255),
    created_date    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status          INTEGER,
    subject         VARCHAR(255),
    CONSTRAINT notification_pkey PRIMARY KEY (notification_id)
);

CREATE TABLE ownership
(
    ownership_id BIGINT NOT NULL,
    property_id  BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    end_time     TIMESTAMP WITHOUT TIME ZONE,
    is_deleted   BOOLEAN DEFAULT FALSE,
    start_time   TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(255),
    type         VARCHAR(255),
    CONSTRAINT ownership_pkey PRIMARY KEY (ownership_id, property_id, user_id)
);

CREATE TABLE payment_methods
(
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT payment_methods_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE point
(
    point_id           BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    point_created_date VARCHAR(255),
    point_price        FLOAT8,
    point_status       SMALLINT,
    CONSTRAINT point_pkey PRIMARY KEY (point_id)
);

CREATE TABLE property_image
(
    image_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN DEFAULT FALSE,
    link        TEXT,
    property_id BIGINT,
    CONSTRAINT property_image_pkey PRIMARY KEY (image_id)
);

CREATE TABLE reservation
(
    reservation_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    checkin             TIMESTAMP WITHOUT TIME ZONE,
    checkout            TIMESTAMP WITHOUT TIME ZONE,
    is_deleted          BOOLEAN DEFAULT FALSE,
    note                VARCHAR(255),
    number_night        FLOAT8,
    price_per_night     FLOAT8,
    status              VARCHAR(255),
    time_off_deposit_id BIGINT,
    total_price         FLOAT8,
    type                VARCHAR(255),
    user_id             BIGINT,
    CONSTRAINT reservation_pkey PRIMARY KEY (reservation_id)
);

CREATE TABLE resort
(
    resort_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted  BOOLEAN DEFAULT FALSE,
    location_id BIGINT,
    resort_name VARCHAR(255),
    CONSTRAINT resort_pkey PRIMARY KEY (resort_id)
);

CREATE TABLE resort_image
(
    image_resort_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted      BOOLEAN DEFAULT FALSE,
    link            TEXT,
    resort_id       BIGINT,
    CONSTRAINT resort_image_pkey PRIMARY KEY (image_resort_id)
);

CREATE TABLE role
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL,
    name    VARCHAR(255)                                           NOT NULL,
    status  BOOLEAN                                                NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (role_id)
);

CREATE TABLE time_off_deposit
(
    time_off_deposit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    end_time            TIMESTAMP WITHOUT TIME ZONE,
    is_deleted          BOOLEAN DEFAULT FALSE,
    number_night        FLOAT8,
    price_per_night     FLOAT8,
    start_time          TIMESTAMP WITHOUT TIME ZONE,
    status              VARCHAR(255),
    type                VARCHAR(255),
    vacation_id         BIGINT,
    CONSTRAINT time_off_deposit_pkey PRIMARY KEY (time_off_deposit_id)
);

CREATE TABLE token
(
    token_id        BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 9) NOT NULL,
    expiration_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status          VARCHAR(255)                                           NOT NULL,
    token_type      VARCHAR(255)                                           NOT NULL,
    value           VARCHAR(255)                                           NOT NULL,
    user_id         BIGINT,
    CONSTRAINT token_pkey PRIMARY KEY (token_id)
);

CREATE TABLE transaction_log
(
    transact_log_id  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
    amount_point     BIGINT                                                 NOT NULL,
    commission       FLOAT8,
    created_on       VARCHAR(255),
    from_total_point FLOAT8,
    to_total_point   FLOAT8,
    wallet_from      BIGINT                                                 NOT NULL,
    wallet_to        BIGINT                                                 NOT NULL,
    CONSTRAINT transaction_log_pkey PRIMARY KEY (transact_log_id)
);

CREATE TABLE transaction_top_up_wallet
(
    wallet_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount                INTEGER,
    payment_date          VARCHAR(255),
    status                BOOLEAN,
    wallet_id             BIGINT,
    CONSTRAINT transaction_top_up_wallet_pkey PRIMARY KEY (wallet_transaction_id)
);

CREATE TABLE users
(
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL,
    avatar         VARCHAR(255),
    dob            date                                                   NOT NULL,
    email          VARCHAR(255)                                           NOT NULL,
    email_verified BOOLEAN,
    full_name      VARCHAR(255),
    gender         VARCHAR(255)                                           NOT NULL,
    password_hash  VARCHAR(255)                                           NOT NULL,
    phone          VARCHAR(255),
    phone_verified BOOLEAN,
    status         VARCHAR(255)                                           NOT NULL,
    username       VARCHAR(255)                                           NOT NULL,
    role_id        BIGINT,
    wallet_id      BIGINT,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE vacation
(
    vacation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    end_time    TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN DEFAULT FALSE,
    property_id BIGINT,
    start_time  TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255),
    CONSTRAINT vacation_pkey PRIMARY KEY (vacation_id)
);

CREATE TABLE wallet
(
    wallet_id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL,
    status      BOOLEAN,
    total_point FLOAT8,
    CONSTRAINT wallet_pkey PRIMARY KEY (wallet_id)
);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

ALTER TABLE role
    ADD CONSTRAINT uk_8sewwnpamngi6b1dwaa88askk UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uk_1vggin5xlv1ptduwmtp1rm16 UNIQUE (wallet_id);

ALTER TABLE users
    ADD CONSTRAINT uk_6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uk_r43af9ap4edm43mmtq01oddj6 UNIQUE (username);

CREATE TABLE in_room_amenity_properties
(
    in_room_amenity_in_room_amenity_id BIGINT NOT NULL,
    properties_property_id             BIGINT NOT NULL
);

CREATE TABLE property_in_room_amenities
(
    property_property_id                 BIGINT NOT NULL,
    in_room_amenities_in_room_amenity_id BIGINT NOT NULL
);

CREATE TABLE resort_amenities
(
    resort_resort_id            BIGINT NOT NULL,
    amenities_resort_amenity_id BIGINT NOT NULL
);

CREATE TABLE resort_amenity_resorts
(
    resort_amenity_resort_amenity_id BIGINT NOT NULL,
    resorts_resort_id                BIGINT NOT NULL
);

CREATE TABLE user_blocked
(
    user_id         BIGINT NOT NULL,
    blocked_user_id BIGINT NOT NULL
);

ALTER TABLE user_blocked
    ADD CONSTRAINT fk1wp478xhxe2jjsagyb0vnrixm FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users
    ADD CONSTRAINT fk2ndfo1foff7a36v7f6sst12ix FOREIGN KEY (wallet_id) REFERENCES wallet (wallet_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_blocked
    ADD CONSTRAINT fk3ft7jt92le6bivrrwj25f87i9 FOREIGN KEY (blocked_user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE resort_image
    ADD CONSTRAINT fk425gj07fjehxa5c212fsh8tat FOREIGN KEY (resort_id) REFERENCES resort (resort_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users
    ADD CONSTRAINT fk4qu1gr772nnf6ve5af002rwya FOREIGN KEY (role_id) REFERENCES role (role_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE property_in_room_amenities
    ADD CONSTRAINT fk5k1ef368undq4t7ffm2gqs4hn FOREIGN KEY (property_property_id) REFERENCES property (property_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE resort_amenity_resorts
    ADD CONSTRAINT fk60qwky8qxksw3cxc1nuumtri2 FOREIGN KEY (resort_amenity_resort_amenity_id) REFERENCES resort_amenity (resort_amenity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE message
    ADD CONSTRAINT fk6yskk3hxw5sklwgi25y6d5u1l FOREIGN KEY (conversation_id) REFERENCES conversation (conversation_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE resort_amenity_resorts
    ADD CONSTRAINT fk88d76384cjuxbfh518vfublbu FOREIGN KEY (resorts_resort_id) REFERENCES resort (resort_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE property_image
    ADD CONSTRAINT fk8myddv2ina4svuo189ju03v9o FOREIGN KEY (property_id) REFERENCES property (property_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE conversation_participant
    ADD CONSTRAINT fk93dv599s56uqs8xslhdp3arya FOREIGN KEY (conversation_id) REFERENCES conversation (conversation_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE vacation
    ADD CONSTRAINT fk9dyxp921oa6kje82qj1ve8i5e FOREIGN KEY (property_id) REFERENCES property (property_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE transaction_log
    ADD CONSTRAINT fk9gwu1il3bvfykqq8alklck4nm FOREIGN KEY (wallet_to) REFERENCES wallet (wallet_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE resort_amenities
    ADD CONSTRAINT fkalj1ho08jdx4cclf6itbxqspr FOREIGN KEY (amenities_resort_amenity_id) REFERENCES resort_amenity (resort_amenity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE property_in_room_amenities
    ADD CONSTRAINT fkba2hmtws3keexcei2hqw2yjmc FOREIGN KEY (in_room_amenities_in_room_amenity_id) REFERENCES in_room_amenity (in_room_amenity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE in_room_amenity_properties
    ADD CONSTRAINT fkbhkfw5rham71jm1nwprd7efpv FOREIGN KEY (properties_property_id) REFERENCES property (property_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE ownership
    ADD CONSTRAINT fkbi00wjrnaelovls4rkdbwqakd FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE resort_amenities
    ADD CONSTRAINT fkbshql2a36s4mye8a03p5a0bmf FOREIGN KEY (resort_resort_id) REFERENCES resort (resort_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE property
    ADD CONSTRAINT fkeqi0saw6kypvbw7tf91w64kc6 FOREIGN KEY (property_type_id) REFERENCES property_type (property_type_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE conversation_participant
    ADD CONSTRAINT fkfhu6wpoqip0lkdrpwj2xbfgan FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE in_room_amenity_properties
    ADD CONSTRAINT fkhm6s4tmftf98lmcuy9d9kcab6 FOREIGN KEY (in_room_amenity_in_room_amenity_id) REFERENCES in_room_amenity (in_room_amenity_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE in_room_amenity
    ADD CONSTRAINT fkisxhjndasb7uop3xr4k0hn0y1 FOREIGN KEY (in_room_amenity_type_id) REFERENCES in_room_amenity_type (in_room_amenity_type_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE token
    ADD CONSTRAINT fkj8rfw4x0wjjyibfqq566j4qng FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE ownership
    ADD CONSTRAINT fkkbbfua534r45dt4wlm16g7ofc FOREIGN KEY (ownership_id) REFERENCES contract_image (contract_image_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE resort_amenity
    ADD CONSTRAINT fkkjtk9e5y4owj1yp6vq7nj4i9t FOREIGN KEY (resort_amenity_type_id) REFERENCES resort_amenity_type (resort_amenity_type_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE ownership
    ADD CONSTRAINT fkm8w7x5y7erg1d0hjjlvsc6tq2 FOREIGN KEY (property_id) REFERENCES property (property_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE property
    ADD CONSTRAINT fkmev1nt4mgdy54tjq6tjmq15v FOREIGN KEY (property_view_id) REFERENCES property_view (property_view_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE transaction_top_up_wallet
    ADD CONSTRAINT fknqdqmd1n5pvv07p208b0ux9nx FOREIGN KEY (wallet_id) REFERENCES wallet (wallet_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE reservation
    ADD CONSTRAINT fko5s3vw420ytode1x9uxmqk1eb FOREIGN KEY (time_off_deposit_id) REFERENCES time_off_deposit (time_off_deposit_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE property_type
    ADD CONSTRAINT fkrc8ws61m5w1bcjw77luqox4y2 FOREIGN KEY (resort_id) REFERENCES resort (resort_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE reservation
    ADD CONSTRAINT fkrea93581tgkq61mdl13hehami FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE resort
    ADD CONSTRAINT fksmywtj3mrm0276s0r9mflvbc1 FOREIGN KEY (location_id) REFERENCES location (location_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE money_transfer
    ADD CONSTRAINT fkt1ewjje3jcce0qewwjhpaj416 FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE time_off_deposit
    ADD CONSTRAINT fkt8sfbo9nocujfv4o9w1904wat FOREIGN KEY (vacation_id) REFERENCES vacation (vacation_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE transaction_log
    ADD CONSTRAINT fktlrk6odkeww1jh23lc0232e0y FOREIGN KEY (wallet_from) REFERENCES wallet (wallet_id) ON UPDATE NO ACTION ON DELETE NO ACTION;