ALTER TABLE rating
    ADD rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE rating
    ADD CONSTRAINT FK_RATING_ON_RATING FOREIGN KEY (rating_id) REFERENCES booking (book_id);

ALTER TABLE available_time
    DROP COLUMN create_date;

-- Fix
ALTER TABLE rating
    DROP CONSTRAINT pk_rating;

ALTER TABLE rating
    ADD CONSTRAINT pk_rating PRIMARY KEY (rating_id);