CREATE TABLE user_reaction_post
(
    is_like    BOOLEAN NOT NULL,
    is_dislike BOOLEAN NOT NULL,
    user_id    BIGINT  NOT NULL,
    post_id    BIGINT  NOT NULL,
    CONSTRAINT pk_user_reaction_post PRIMARY KEY (user_id, post_id)
);

CREATE TABLE post
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    content     TEXT                            NOT NULL,
    date_posted TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

ALTER TABLE user_reaction_post
    ADD CONSTRAINT FK_USER_REACTION_POST_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE user_reaction_post
    ADD CONSTRAINT FK_USER_REACTION_POST_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_USERID FOREIGN KEY (user_id) REFERENCES users (user_id);