CREATE TABLE all_booking_refund_owner_transaction_log
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_booking_id BIGINT                                  NOT NULL,
    to_member_id    BIGINT                                  NOT NULL,
    amount          DOUBLE PRECISION,
    result_code     INTEGER,
    detail          VARCHAR(255),
    created_on      VARCHAR(255),
    member_balance  DOUBLE PRECISION,
    commission      DOUBLE PRECISION,
    type            INTEGER,
    CONSTRAINT pk_all_booking_refund_owner_transaction_log PRIMARY KEY (id)
);

CREATE TABLE all_pay_booking_transaction_log
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_member_id BIGINT                                  NOT NULL,
    to_booking_id  BIGINT                                  NOT NULL,
    amount         DOUBLE PRECISION,
    result_code    INTEGER,
    detail         VARCHAR(255),
    created_on     VARCHAR(255),
    from_balance   DOUBLE PRECISION,
    type           INTEGER,
    CONSTRAINT pk_all_pay_booking_transaction_log PRIMARY KEY (id)
);

CREATE TABLE apartment_wallet
(
    total_point DOUBLE PRECISION,
    property_id BIGINT       NOT NULL,
    room_id     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_apartment_wallet PRIMARY KEY (property_id, room_id)
);

CREATE TABLE available_time
(
    available_time_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    price_per_night   DOUBLE PRECISION                        NOT NULL,
    is_deleted        BOOLEAN DEFAULT FALSE                   NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    time_frame_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_available_time PRIMARY KEY (available_time_id)
);

CREATE TABLE booking
(
    book_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id    BIGINT                                  NOT NULL,
    room_id        VARCHAR(255)                            NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    check_in_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    check_out_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status         INTEGER                                 NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (book_id)
);

CREATE TABLE booking_detail
(
    book_detail_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_id          BIGINT                                  NOT NULL,
    property_id      BIGINT                                  NOT NULL,
    room_id          VARCHAR(255)                            NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    check_in_date    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    check_out_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    number_of_guests INTEGER                                 NOT NULL,
    total_point      DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_booking_detail PRIMARY KEY (book_detail_id)
);

CREATE TABLE co_owner
(
    start_time  TIMESTAMP WITHOUT TIME ZONE,
    end_time    TIMESTAMP WITHOUT TIME ZONE,
    type        VARCHAR(255) NOT NULL,
    status      VARCHAR(255) NOT NULL,
    is_deleted  BOOLEAN DEFAULT FALSE,
    property_id BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    room_id     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_co_owner PRIMARY KEY (property_id, user_id, room_id)
);

CREATE TABLE time_frame
(
    time_frame_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_deleted    BOOLEAN DEFAULT FALSE,
    status        VARCHAR(255)                            NOT NULL,
    property_id   BIGINT                                  NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    room_id       VARCHAR(255),
    CONSTRAINT pk_time_frame PRIMARY KEY (time_frame_id)
);

CREATE TABLE property_co_owners
(
    property_property_id  BIGINT       NOT NULL,
    co_owners_property_id BIGINT       NOT NULL,
    co_owners_room_id     VARCHAR(255) NOT NULL,
    co_owners_user_id     BIGINT       NOT NULL
);

CREATE TABLE property_type_properties
(
    property_type_property_type_id BIGINT NOT NULL,
    properties_property_id         BIGINT NOT NULL
);

ALTER TABLE reservation
    ADD available_time_id BIGINT;

ALTER TABLE resort
    ADD resort_description VARCHAR;

ALTER TABLE resort
    ADD resort_status VARCHAR(255);

ALTER TABLE money_transfer
    ADD total_point DOUBLE PRECISION;

ALTER TABLE transaction_top_up_wallet
    ADD type INTEGER;

ALTER TABLE in_room_amenity
    ADD in_room_amenity_link_icon TEXT;

ALTER TABLE in_room_amenity
    ALTER COLUMN in_room_amenity_link_icon SET NOT NULL;

ALTER TABLE property
    ADD number_double_beds INTEGER;

ALTER TABLE property
    ADD number_queen_beds INTEGER;

ALTER TABLE property
    ADD number_single_beds INTEGER;

ALTER TABLE property
    ADD property_description VARCHAR(255);

ALTER TABLE property
    ADD property_name VARCHAR(255);

ALTER TABLE property
    ADD resort_id BIGINT;

ALTER TABLE property
    ALTER COLUMN property_name SET NOT NULL;

ALTER TABLE resort_amenity
    ADD resort_amenity_link_icon TEXT;

ALTER TABLE resort_amenity
    ALTER COLUMN resort_amenity_link_icon SET NOT NULL;

ALTER TABLE property
    ALTER COLUMN resort_id SET NOT NULL;

ALTER TABLE property_co_owners
    ADD CONSTRAINT uc_property_co_owners_copridcoroidcousid UNIQUE (co_owners_property_id, co_owners_room_id, co_owners_user_id);

ALTER TABLE property_type_properties
    ADD CONSTRAINT uc_property_type_properties_properties_property UNIQUE (properties_property_id);

ALTER TABLE apartment_wallet
    ADD CONSTRAINT FK_APARTMENT_WALLET_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (property_id);

ALTER TABLE available_time
    ADD CONSTRAINT FK_AVAILABLE_TIME_ON_TIME_FRAME FOREIGN KEY (time_frame_id) REFERENCES time_frame (time_frame_id);

ALTER TABLE booking_detail
    ADD CONSTRAINT FK_BOOKING_DETAIL_ON_BOOK FOREIGN KEY (book_id) REFERENCES booking (book_id);

ALTER TABLE booking_detail
    ADD CONSTRAINT FK_BOOKING_DETAIL_ON_PRIDUSIDROID FOREIGN KEY (property_id, user_id, room_id) REFERENCES co_owner (property_id, user_id, room_id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (property_id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);


ALTER TABLE contract_image
DROP
CONSTRAINT IF EXISTS FK_CONTRACT_IMAGE_ON_PRIDUSIDROID;

ALTER TABLE contract_image
    ADD CONSTRAINT FK_CONTRACT_IMAGE_ON_PRIDUSIDROID FOREIGN KEY (property_id, user_id, room_id) REFERENCES co_owner (property_id, user_id, room_id);

ALTER TABLE co_owner
    ADD CONSTRAINT FK_CO_OWNER_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (property_id);

ALTER TABLE co_owner
    ADD CONSTRAINT FK_CO_OWNER_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_AVAILABLE_TIME FOREIGN KEY (available_time_id) REFERENCES available_time (available_time_id);

ALTER TABLE time_frame
    ADD CONSTRAINT FK_TIME_FRAME_ON_PRIDUSIDROID FOREIGN KEY (property_id, user_id, room_id) REFERENCES co_owner (property_id, user_id, room_id);

ALTER TABLE property
    ADD CONSTRAINT FK_PROPERTY_ON_RESORT FOREIGN KEY (resort_id) REFERENCES resort (resort_id);

ALTER TABLE property_co_owners
    ADD CONSTRAINT fk_procoown_on_co_owner FOREIGN KEY (co_owners_property_id, co_owners_user_id, co_owners_room_id) REFERENCES co_owner (property_id, user_id, room_id);

ALTER TABLE property_co_owners
    ADD CONSTRAINT fk_procoown_on_property FOREIGN KEY (property_property_id) REFERENCES property (property_id);

ALTER TABLE property_type_properties
    ADD CONSTRAINT fk_protyppro_on_property FOREIGN KEY (properties_property_id) REFERENCES property (property_id);

ALTER TABLE property_type_properties
    ADD CONSTRAINT fk_protyppro_on_property_type FOREIGN KEY (property_type_property_type_id) REFERENCES property_type (property_type_id);

ALTER TABLE contract_image
DROP
CONSTRAINT fk_contract_image_on_pridusidroid;

ALTER TABLE ownership
DROP
CONSTRAINT fk_ownership_on_property;

ALTER TABLE ownership
DROP
CONSTRAINT fk_ownership_on_user;

ALTER TABLE reservation
DROP
CONSTRAINT fk_reservation_on_time_off_deposit;

ALTER TABLE time_off_deposit
DROP
CONSTRAINT fk_time_off_deposit_on_vacation_unit;

ALTER TABLE vacation_unit
DROP
CONSTRAINT fk_vacation_unit_on_pridusidroid;

DROP TABLE ownership CASCADE;

DROP TABLE time_off_deposit CASCADE;

DROP TABLE vacation_unit CASCADE;

ALTER TABLE property
DROP
COLUMN number_qeen_beds;

ALTER TABLE transaction_top_up_wallet
DROP
COLUMN status;

ALTER TABLE reservation
DROP
COLUMN time_off_deposit_id;

ALTER TABLE contract_image
    ALTER COLUMN is_deleted SET NOT NULL;

ALTER TABLE property_image
    ALTER COLUMN is_deleted SET NOT NULL;

ALTER TABLE property_image
    ALTER COLUMN link SET NOT NULL;

ALTER TABLE resort_image
    ALTER COLUMN link SET NOT NULL;

ALTER TABLE contract_image
    ALTER COLUMN property_id SET NOT NULL;

ALTER TABLE property_image
    ALTER COLUMN property_id SET NOT NULL;

ALTER TABLE resort_image
    ALTER COLUMN resort_id SET NOT NULL;

ALTER TABLE resort
    ALTER COLUMN resort_name SET NOT NULL;

ALTER TABLE contract_image
    ALTER COLUMN room_id SET NOT NULL;

ALTER TABLE contract_image
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE in_room_amenity
    ALTER COLUMN in_room_amenity_name SET NOT NULL;

ALTER TABLE in_room_amenity_type
    ALTER COLUMN in_room_amenity_type_name SET NOT NULL;

ALTER TABLE in_room_amenity
    ALTER COLUMN is_deleted SET NOT NULL;

ALTER TABLE in_room_amenity_type
    ALTER COLUMN is_deleted SET NOT NULL;

ALTER TABLE property
    ALTER COLUMN is_deleted SET NOT NULL;

ALTER TABLE resort_amenity_type
    ALTER COLUMN is_deleted SET NOT NULL;

ALTER TABLE property
    ALTER COLUMN number_baths_room SET NOT NULL;

ALTER TABLE property
    ALTER COLUMN number_beds_room SET NOT NULL;

ALTER TABLE property
    ALTER COLUMN property_type_id SET NOT NULL;

ALTER TABLE property_type
    ALTER COLUMN property_type_name SET NOT NULL;

ALTER TABLE property
    ALTER COLUMN property_view_id SET NOT NULL;

ALTER TABLE property_view
    ALTER COLUMN property_view_name SET NOT NULL;

ALTER TABLE resort_amenity
    ALTER COLUMN resort_amenity_type_id SET NOT NULL;

ALTER TABLE property
    ALTER COLUMN status SET NOT NULL;