CREATE TABLE all_booking_refund_owner_transaction_log
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_booking_id BIGINT                                  NOT NULL,
    to_member_id    BIGINT                                  NOT NULL,
    amount          DOUBLE PRECISION,
    result_code     INTEGER,
    detail          VARCHAR(255),
    created_on      VARCHAR(255),
    member_balance  DOUBLE PRECISION,
    commission      DOUBLE PRECISION,
    type            INTEGER,
    CONSTRAINT pk_all_booking_refund_owner_transaction_log PRIMARY KEY (id)
);

CREATE TABLE all_pay_booking_transaction_log
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_member_id BIGINT                                  NOT NULL,
    to_booking_id  BIGINT                                  NOT NULL,
    amount         DOUBLE PRECISION,
    result_code    INTEGER,
    detail         VARCHAR(255),
    created_on     VARCHAR(255),
    from_balance   DOUBLE PRECISION,
    type           INTEGER,
    CONSTRAINT pk_all_pay_booking_transaction_log PRIMARY KEY (id)
);

CREATE TABLE apartment_wallet
(
    total_point DOUBLE PRECISION,
    property_id BIGINT       NOT NULL,
    room_id     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_apartment_wallet PRIMARY KEY (property_id, room_id)
);

CREATE TABLE booking
(
    book_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id    BIGINT                                  NOT NULL,
    room_id        VARCHAR(255)                            NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    check_in_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    check_out_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status         INTEGER                                 NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (book_id)
);

CREATE TABLE booking_detail
(
    book_detail_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_id          BIGINT                                  NOT NULL,
    property_id      BIGINT                                  NOT NULL,
    room_id          VARCHAR(255)                            NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    check_in_date    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    check_out_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    number_of_guests INTEGER                                 NOT NULL,
    total_point      DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_booking_detail PRIMARY KEY (book_detail_id)
);

ALTER TABLE money_transfer
    ADD total_point DOUBLE PRECISION;

ALTER TABLE transaction_top_up_wallet
    ADD type INTEGER;

ALTER TABLE apartment_wallet
    ADD CONSTRAINT FK_APARTMENT_WALLET_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (property_id);

ALTER TABLE booking_detail
    ADD CONSTRAINT FK_BOOKING_DETAIL_ON_BOOK FOREIGN KEY (book_id) REFERENCES booking (book_id);

ALTER TABLE booking_detail
    ADD CONSTRAINT FK_BOOKING_DETAIL_ON_PRIDUSIDROID FOREIGN KEY (property_id, user_id, room_id) REFERENCES co_owner (property_id, user_id, room_id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES property (property_id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE contract_image
    ADD CONSTRAINT FK_CONTRACT_IMAGE_ON_PRIDUSIDROID FOREIGN KEY (property_id, user_id, room_id) REFERENCES co_owner (property_id, user_id, room_id);

DROP TABLE admin_wallet_1 CASCADE;

ALTER TABLE transaction_top_up_wallet
DROP
COLUMN status;