CREATE TABLE user_of_booking
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name    VARCHAR(255),
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    book_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_of_booking PRIMARY KEY (id)
);

ALTER TABLE booking
    ADD price DOUBLE PRECISION;

ALTER TABLE booking
    ALTER COLUMN price SET NOT NULL;

ALTER TABLE contract_image
    ADD CONSTRAINT FK_CONTRACT_IMAGE_ON_PRIDUSIDROID FOREIGN KEY (property_id, user_id, room_id) REFERENCES co_owner (property_id, user_id, room_id);

ALTER TABLE user_of_booking
    ADD CONSTRAINT FK_USER_OF_BOOKING_ON_BOOK FOREIGN KEY (book_id) REFERENCES booking (book_id);

ALTER TABLE property_co_owners
    DROP CONSTRAINT fk_procoown_on_co_owner;

ALTER TABLE property_co_owners
    DROP CONSTRAINT fk_procoown_on_property;

DROP TABLE property_co_owners CASCADE;

ALTER TABLE transaction_log
    DROP COLUMN commission;

ALTER TABLE time_frame
    DROP COLUMN end_time;

ALTER TABLE time_frame
    DROP COLUMN start_time;

ALTER TABLE available_time
    ALTER COLUMN end_time SET NOT NULL;

ALTER TABLE resort
    ALTER COLUMN resort_description TYPE VARCHAR(255) USING (resort_description::VARCHAR(255));

ALTER TABLE all_booking_refund_owner_transaction_log
    DROP COLUMN result_code;

ALTER TABLE all_booking_refund_owner_transaction_log
    DROP COLUMN type;

ALTER TABLE all_booking_refund_owner_transaction_log
    ADD result_code SMALLINT;

ALTER TABLE all_pay_booking_transaction_log
    DROP COLUMN result_code;

ALTER TABLE all_pay_booking_transaction_log
    DROP COLUMN type;

ALTER TABLE all_pay_booking_transaction_log
    ADD result_code SMALLINT;

ALTER TABLE available_time
    ALTER COLUMN start_time SET NOT NULL;

ALTER TABLE booking
    DROP COLUMN status;

ALTER TABLE booking
    ADD status SMALLINT NOT NULL;

ALTER TABLE all_booking_refund_owner_transaction_log
    ADD type SMALLINT;

ALTER TABLE all_pay_booking_transaction_log
    ADD type SMALLINT;

ALTER TABLE transaction_top_up_wallet
    DROP COLUMN type;

ALTER TABLE transaction_top_up_wallet
    ADD type SMALLINT;