CREATE TABLE notification_firebase
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fcm_token VARCHAR(255),
    user_id   BIGINT,
    CONSTRAINT pk_notification_firebase PRIMARY KEY (id)
);

CREATE TABLE notification_user
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    link    VARCHAR(255),
    is_read BOOLEAN,
    content VARCHAR(255),
    CONSTRAINT pk_notification_user PRIMARY KEY (id)
);

ALTER TABLE booking
    ADD actual_price DOUBLE PRECISION;

ALTER TABLE booking
    ADD available_time_id BIGINT;

ALTER TABLE booking
    ADD commission DOUBLE PRECISION;

ALTER TABLE booking
    ADD owner_id BIGINT;

ALTER TABLE booking
    ADD total_days BIGINT;

ALTER TABLE booking
    ADD user_booking_id BIGINT;

ALTER TABLE booking
    ALTER COLUMN actual_price SET NOT NULL;

ALTER TABLE booking
    ALTER COLUMN available_time_id SET NOT NULL;

ALTER TABLE booking
    ALTER COLUMN commission SET NOT NULL;

ALTER TABLE booking
    ALTER COLUMN owner_id SET NOT NULL;

ALTER TABLE booking
    ALTER COLUMN total_days SET NOT NULL;

ALTER TABLE booking
    ALTER COLUMN user_booking_id SET NOT NULL;

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_AVAILABLE_TIME FOREIGN KEY (available_time_id) REFERENCES available_time (available_time_id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (user_id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_USER_BOOKING FOREIGN KEY (user_booking_id) REFERENCES users (user_id);

ALTER TABLE booking_detail
    DROP CONSTRAINT fk_booking_detail_on_book;

ALTER TABLE booking_detail
    DROP CONSTRAINT fk_booking_detail_on_pridusidroid;

ALTER TABLE booking
    DROP CONSTRAINT fk_booking_on_property;

ALTER TABLE booking
    DROP CONSTRAINT fk_booking_on_user;

DROP TABLE booking_detail CASCADE;

ALTER TABLE booking
    DROP COLUMN property_id;

ALTER TABLE booking
    DROP COLUMN room_id;

ALTER TABLE booking
    DROP COLUMN user_id;