name: CI - Build Backend

on:
  pull_request:
    branches: [ master ]

env:
  POSTGRESQL_VERSION: 13.1
  POSTGRESQL_DB: holiday-swap
  POSTGRESQL_USER: holiday-swap
  POSTGRESQL_PASSWORD: password
  JAVA_VERSION: 17
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  TWILIO_TRIAL_NUMBER: ${{ secrets.TWILIO_TRIAL_NUMBER }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Env
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - 5672:5672
          - 15672:15672
          - 61613:61613
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        credentials:
            password: password


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify